on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build docker image
      run: docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t microvisor-weather-image .
    - name: Build code
      run: docker run --rm -v $(pwd)/:/home/mvisor/project/ --env MICROVISOR_GITHUB_ACTION_WEATHER_TEST=true --name microvisor-weather microvisor-weather-image
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mv-weather-device-demo
        path: ${{ github.workspace }}/build/App/mv-weather-device-demo.*
